# Generated by Django 4.2.1 on 2025-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('cook_time', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'простая'), ('medium', 'средняя'), ('hard', 'сложная')], default='easy', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='recipes_rec_created_57db65_idx')],
            },
        ),
    ]
