# Generated by Django 4.2.1 on 2025-10-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_reaction_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'permissions': [('can_moderate_comments', 'Может модерировать комментарии')]},
        ),
    ]
